/*
Deployment script for C:\AMOSNG\GRADINGSYSTEM\GRADESYSTEM\APP_DATA\GRADESDB.MDF

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "C:\AMOSNG\GRADINGSYSTEM\GRADESYSTEM\APP_DATA\GRADESDB.MDF"
:setvar DefaultFilePrefix "C_\AMOSNG\GRADINGSYSTEM\GRADESYSTEM\APP_DATA\GRADESDB.MDF_"
:setvar DefaultDataPath "C:\Users\kontoteamrocky\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\v11.0\"
:setvar DefaultLogPath "C:\Users\kontoteamrocky\AppData\Local\Microsoft\Microsoft SQL Server Local DB\Instances\v11.0\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO

IF (SELECT OBJECT_ID('tempdb..#tmpErrors')) IS NOT NULL DROP TABLE #tmpErrors
GO
CREATE TABLE #tmpErrors (Error int)
GO
SET XACT_ABORT ON
GO
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
GO
BEGIN TRANSACTION
GO
PRINT N'Dropping [dbo].[FK_Grades_Questions]...';


GO
ALTER TABLE [dbo].[Grades] DROP CONSTRAINT [FK_Grades_Questions];


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Starting rebuilding table [dbo].[Grades]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_Grades] (
    [Id]         INT      IDENTITY (1, 1) NOT NULL,
    [Date]       DATETIME NOT NULL,
    [QuestionId] INT      NOT NULL,
    [Answer]     INT      NOT NULL,
    [Week]       INT      NOT NULL,
    PRIMARY KEY CLUSTERED ([Id] ASC)
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[Grades])
    BEGIN
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_Grades] ON;
        INSERT INTO [dbo].[tmp_ms_xx_Grades] ([Id], [Date], [QuestionId], [Answer], [Week])
        SELECT   [Id],
                 [Date],
                 [QuestionId],
                 [Answer],
                 [Week]
        FROM     [dbo].[Grades]
        ORDER BY [Id] ASC;
        SET IDENTITY_INSERT [dbo].[tmp_ms_xx_Grades] OFF;
    END

DROP TABLE [dbo].[Grades];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_Grades]', N'Grades';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO
PRINT N'Creating [dbo].[FK_Grades_Questions]...';


GO
ALTER TABLE [dbo].[Grades] WITH NOCHECK
    ADD CONSTRAINT [FK_Grades_Questions] FOREIGN KEY ([QuestionId]) REFERENCES [dbo].[Questions] ([Id]);


GO
IF @@ERROR <> 0
   AND @@TRANCOUNT > 0
    BEGIN
        ROLLBACK;
    END

IF @@TRANCOUNT = 0
    BEGIN
        INSERT  INTO #tmpErrors (Error)
        VALUES                 (1);
        BEGIN TRANSACTION;
    END


GO

IF EXISTS (SELECT * FROM #tmpErrors) ROLLBACK TRANSACTION
GO
IF @@TRANCOUNT>0 BEGIN
PRINT N'The transacted portion of the database update succeeded.'
COMMIT TRANSACTION
END
ELSE PRINT N'The transacted portion of the database update failed.'
GO
DROP TABLE #tmpErrors
GO
PRINT N'Checking existing data against newly created constraints';


GO
USE [$(DatabaseName)];


GO
ALTER TABLE [dbo].[Grades] WITH CHECK CHECK CONSTRAINT [FK_Grades_Questions];


GO
PRINT N'Update complete.';


GO
